services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: host
    environment:
      - LIVEKIT_KEYS=${LIVEKIT_KEYS}
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
