# Generated by Django 6.0.7 on 2026-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=64)),
                ('broadcaster_name', models.CharField(max_length=64)),
                ('egress_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='recording', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
